services:
  test:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - XRECHNUNG_TESTSUITE_PATH=/app/vendor/testsuite
    tmpfs:
      - /tmp

  verapdf:
    image: verapdf/rest:latest
    ports:
      - "8080:8080"

  mustang:
    build: docker/mustang

volumes:
  bundle_cache:
